### ISSUE TITLE
Time remaining value missing

### ISSUE THREAD

**Issue by sjthespian** [quielb/hass-airscape#16]
I have some code in node red that sets a flow variable based on the time remaining on my Airscape fan, and that has stopped working. when I look at the device I no longer see the attribute. Did something change in the HA internals that is keeping this value from being returned? It used to be in the `Shutoff Timer` attribute:
```
flow.set('whf_timeremaining',msg.data.new_state.attributes["Shutoff Timer"]);;;
```

My device no longer has any attribute like that:
| Entity | State | Attributes |
| -- | -- | -- |
| fan.whf<br/>WHF | off | actions_enabled: true<br/> actions_last_update: 2022-05-20T21:22:57.177741<br/> ran_else: 0<br/> ran_then: 0<br/> run_at_startup: false<br/> running: false<br/> status_enabled: true<br/> status_last_finished: 2022-05-20T21:21:32<br/> status_last_run: 2022-05-20T21:21:32<br/> status_last_update: 2022-05-20T21:22:58.362678<br/> friendly_name: WHF<br/> supported_features: 0 |

**Comment by quielb** [comment]
Same issue as #15
