### ISSUE TITLE
Deprecated Constants in HA Core 2025.1

### ISSUE THREAD

**Issue by gjgeary** [quielb/hass-airscape#20]
Hi Barry,
No rush on this.  Wanted to make you aware of a deprecation that will affect the Airscape Custom Component.

See this log warning...
SUPPORT_SET_SPEED was used from airscape, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/quielb/hass-airscape/issues

Let me know if you need any additional information.  This has been working great for the last year and half.  Thanks for developing this.

Greg Geary

**Comment by quielb** [comment]
Solved with #23

**Comment by gjgeary** [comment]
Hi Barry,

 

Thanks for continuing to support this integration.  It is very much appreciated.

 

Greg Geary
