### ISSUE TITLE
Does this enable speed control too?

### ISSUE THREAD

**Issue by turtlelips** [quielb/hass-airscape#21]
Hello, I found this and am planning on installing an Airscape fan. I was curious if this HA add on enables speed control? Can you keep the manual controls too with this? Thank you

**Comment by tmoran3020** [comment]
Not the author, just a user but yes - it handles speed control and it will poll so it will notice any manual changes done by button or webpage (not instantly, but fairly quickly).

Just make sure you have the right controls package - pretty sure this only works with gen 2 controls, which I believe are no longer the default.

**Comment by quielb** [comment]
Correct. This component does control speed. And yes it only supports Gen2 controls, which are not available for order from the website. You have to call and place an order for them.
