### ISSUE TITLE
Timer control missing

### ISSUE THREAD

**Issue by sjthespian** [quielb/hass-airscape#24]
It looks like the add_time service has gone missing in the 1.0 release. This was added back in #5.

I am only seeing speed_up, slow_down and turn_on_to_minimum in the services list.

Other than that, this new release is looking great. Thanks for all the work on it!

**Comment by quielb** [comment]
As noted in the updated readme the add timer has move from an `action` to a button. That is the "Home Assistant" way to do it. You can change out your `action` call to a button press for the button timer entity and it will function the same.

**Comment by sjthespian** [comment]
As an added piece of this, it looks like the shutdown_timer attribute is missing from the fan as well. Although I see there is a new sensor -- sensor.airscape_1_7whf_timer in my case.

**Comment by quielb** [comment]
Yes, also covered in the readme update. Home assistant has moved away from supporting device attributes in favor of using sensor entities.

**Comment by sjthespian** [comment]
Ok, I'm an idiot... I don't know how I missed that in the Readme. And it's even easier to use than the convoluted logic I was using in my NodeRed flows to manage the timer in the past!

Thanks!!
