### ISSUE TITLE
Fans with less than 10 speeds

### ISSUE THREAD

**Issue by sjthespian** [quielb/hass-airscape#4]
I have an older Airscape fan that only has low, high, and off. Would it be possible to add either the ability to set the speed_list or the number of speeds?

**Comment by quielb** [comment]
This should be possible. I need to rework the how fan speed is managed based on the latest HA update anyway. I will work this in.

**Comment by sjthespian** [comment]
@quielb Have you made any progress on this? I have a workaround for the fan-percent-button-row custom widget, but it's a bit odd to have to set the fan to 18% for low and 27% for high. :-)

**Comment by quielb** [comment]
That sounds a little like a hacky workaround, but glad you got something working. I have a chance to poke at this. I am working on updating the pypi module for this. Once that is done I should be able to work on the HA component.

**Comment by quielb** [comment]
Can you send me the output from ```curl http://<ip of fan>/status.json.cgi```

**Comment by sjthespian** [comment]
The binary data in server_response breaks a lot of json parsers...
```json
{
    "fanspd": 0,
    "doorinprocess": 0,
    "timeremaining": 0,
    "macaddr": "60:CB:FB:00:22:EA",
    "ipaddr": "172.16.42.56",
    "model": "1.7WHF",
    "softver": "2.15.1",
    "interlock1":0,
    "interlock2": 0,
    "cfm": 0,
    "power": 0,
    "inside":-99,
    "attic": 81,
    "oa":-99,
    "server_response": "�_�<\�&;�x���H�3���P��
                                              s�
                                                �
                                                 �",
    "dip_switches": "11110",
    "remote_switch": "1111",
    "setpoint": 0,
    "dns": "172.16.42.1"
    }
```

**Comment by quielb** [comment]
I've updated the Platform. It should correctly account for your 2 speed fan. Please update and confirm. Also take not of the breaking changes.
